# Generated by Django 4.2.16 on 2024-12-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadNode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("province", models.CharField(max_length=100, verbose_name="省份")),
                ("city", models.CharField(max_length=100, verbose_name="城市")),
                ("district", models.CharField(max_length=100, verbose_name="区县")),
                ("node_name", models.CharField(max_length=255, verbose_name="道路节点名称")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述信息"),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最近更新时间"),
                ),
            ],
            options={
                "db_table": "road_nodes",
            },
        ),
        migrations.CreateModel(
            name="TrafficHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="日期")),
                ("time_slot", models.CharField(max_length=50, verbose_name="时间段")),
                ("traffic_value", models.IntegerField(verbose_name="流量值")),
                (
                    "weather_info",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="天气信息"
                    ),
                ),
                (
                    "special_events",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="特殊事件"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_history",
                        to="data_query.roadnode",
                        verbose_name="道路节点",
                    ),
                ),
            ],
            options={
                "db_table": "traffic_history",
            },
        ),
        migrations.CreateModel(
            name="TrafficForecast",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("forecast_date", models.DateField(verbose_name="预测日期")),
                ("time_slot", models.CharField(max_length=50, verbose_name="时间段")),
                ("forecast_value", models.IntegerField(verbose_name="预测流量值")),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="模型版本"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_forecast",
                        to="data_query.roadnode",
                        verbose_name="道路节点",
                    ),
                ),
            ],
            options={
                "db_table": "traffic_forecast",
            },
        ),
    ]
