# Generated by Django 4.2.16 on 2024-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_query", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxiTrace",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("taxi_id", models.CharField(max_length=100, verbose_name="出租车车牌号")),
                ("longitude", models.FloatField(verbose_name="经度")),
                ("latitude", models.FloatField(verbose_name="纬度")),
                ("speed", models.FloatField(verbose_name="速度")),
                ("direction", models.IntegerField(verbose_name="方向")),
                ("gps_time", models.DateTimeField(verbose_name="GPS 时间")),
                ("base_time", models.DateTimeField(verbose_name="基准时间")),
                ("status", models.IntegerField(verbose_name="状态")),
            ],
            options={
                "db_table": "taxi_trace",
            },
        ),
    ]
