# Generated by Django 4.2.16 on 2024-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_query", "0002_taxitrace"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxiInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("taxi_id", models.CharField(max_length=100, verbose_name="出租车车牌号")),
            ],
            options={
                "db_table": "taxi_info",
            },
        ),
    ]
